import os
import subprocess

browsers=["Firefoxfocus","Chrome_Default","Chrome_Incognito","Tor","Dolphin","Brave","Opera","Firefox"]

for i in range(len(browsers)):
	print(f"<----------------------------------------------Artifacts of {browsers[i]} !!!----------------------------------------------------->")
	print("Yahoo.com Data: \n")
	k=subprocess.check_output(f"grep -a -R yahoo.com {browsers[i]} | cut -d : -f -1 | grep domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domainhistogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R yahoo.com {browsers[i]} | cut -d : -f -1 | grep domain.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domain.txt {value}")
	k=subprocess.check_output(f"grep -a -R yahoo.com {browsers[i]} | cut -d : -f -1 | grep email_domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_domain_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R yahoo.com {browsers[i]} | cut -d : -f -1 | grep email_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R yahoo.com {browsers[i]} | cut -d : -f -1 | grep email.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email.txt {value}")
	k=subprocess.check_output(f"grep -a -R yahoo.com {browsers[i]} | cut -d : -f -1 | grep json.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"json.txt {value}")
	k=subprocess.check_output(f"grep -a -R yahoo.com {browsers[i]} | cut -d : -f -1 | grep url_searches.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_searches.txt {value}")
	k=subprocess.check_output(f"grep -a -R yahoo.com {browsers[i]} | cut -d : -f -1 | grep url_services.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_services.txt {value}")
	k=subprocess.check_output(f"grep -a -R yahoo.com {browsers[i]} | cut -d : -f -1 | grep sqlite_carved | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"sqlite.db {value}")
	k=subprocess.check_output(f"grep -a -R yahoo.com {browsers[i]} | cut -d : -f -1 | grep url_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R yahoo.com {browsers[i]} | cut -d : -f -1 | grep url.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url.txt {value}")
	print("\n")
	print("\n")
	print("Twitter.com Data: \n")
	k=subprocess.check_output(f"grep -a -R twitter.com {browsers[i]} | cut -d : -f -1 | grep domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domainhistogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R twitter.com {browsers[i]} | cut -d : -f -1 | grep domain.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domain.txt {value}")
	k=subprocess.check_output(f"grep -a -R twitter.com {browsers[i]} | cut -d : -f -1 | grep email_domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_domain_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R twitter.com {browsers[i]} | cut -d : -f -1 | grep email_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R twitter.com {browsers[i]} | cut -d : -f -1 | grep email.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email.txt {value}")
	k=subprocess.check_output(f"grep -a -R twitter.com {browsers[i]} | cut -d : -f -1 | grep json.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"json.txt {value}")
	k=subprocess.check_output(f"grep -a -R twitter.com {browsers[i]} | cut -d : -f -1 | grep url_searches.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_searches.txt {value}")
	k=subprocess.check_output(f"grep -a -R twitter.com {browsers[i]} | cut -d : -f -1 | grep url_services.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_services.txt {value}")
	k=subprocess.check_output(f"grep -a -R twitter.com {browsers[i]} | cut -d : -f -1 | grep sqlite_carved | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"sqlite.db {value}")
	k=subprocess.check_output(f"grep -a -R twitter.com {browsers[i]} | cut -d : -f -1 | grep url_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R twitter.com {browsers[i]} | cut -d : -f -1 | grep url.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url.txt {value}")
	print("\n")
	print("\n")
	print("Nytimes.com Data: \n")
	k=subprocess.check_output(f"grep -a -R nytimes.com {browsers[i]} | cut -d : -f -1 | grep domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domainhistogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R nytimes.com {browsers[i]} | cut -d : -f -1 | grep domain.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domain.txt {value}")
	k=subprocess.check_output(f"grep -a -R nytimes.com {browsers[i]} | cut -d : -f -1 | grep email_domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_domain_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R nytimes.com {browsers[i]} | cut -d : -f -1 | grep email_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R nytimes.com {browsers[i]} | cut -d : -f -1 | grep email.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email.txt {value}")
	k=subprocess.check_output(f"grep -a -R nytimes.com {browsers[i]} | cut -d : -f -1 | grep json.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"json.txt {value}")
	k=subprocess.check_output(f"grep -a -R nytimes.com {browsers[i]} | cut -d : -f -1 | grep url_searches.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_searches.txt {value}")
	
	k=subprocess.check_output(f"grep -a -R nytimes.com {browsers[i]} | cut -d : -f -1 | grep url_services.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_services.txt {value}")
	
	k=subprocess.check_output(f"grep -a -R nytimes.com {browsers[i]} | cut -d : -f -1 | grep sqlite_carved | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"sqlite.db {value}")
	
	k=subprocess.check_output(f"grep -a -R nytimes.com {browsers[i]} | cut -d : -f -1 | grep url_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_histogram.txt {value}")

	k=subprocess.check_output(f"grep -a -R nytimes.com {browsers[i]} | cut -d : -f -1 | grep url.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url.txt {value}")
	print("\n")
	print("2700chess.com Data: \n")
	k=subprocess.check_output(f"grep -a -R 2700chess.com {browsers[i]} | cut -d : -f -1 | grep domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domainhistogram.txt {value}")
	
	k=subprocess.check_output(f"grep -a -R 2700chess.com {browsers[i]} | cut -d : -f -1 | grep domain.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domain.txt {value}")
	
	k=subprocess.check_output(f"grep -a -R 2700chess.com {browsers[i]} | cut -d : -f -1 | grep email_domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_domain_histogram.txt {value}")
	
	k=subprocess.check_output(f"grep -a -R 2700chess.com {browsers[i]} | cut -d : -f -1 | grep email_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_histogram.txt {value}")
	
	k=subprocess.check_output(f"grep -a -R 2700chess.com {browsers[i]} | cut -d : -f -1 | grep email.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email.txt {value}")
	
	k=subprocess.check_output(f"grep -a -R 2700chess.com {browsers[i]} | cut -d : -f -1 | grep json.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"json.txt {value}")
	
	k=subprocess.check_output(f"grep -a -R 2700chess.com {browsers[i]} | cut -d : -f -1 | grep url_searches.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_searches.txt {value}")
	
	k=subprocess.check_output(f"grep -a -R 2700chess.com {browsers[i]} | cut -d : -f -1 | grep url_services.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_services.txt {value}")
	
	k=subprocess.check_output(f"grep -a -R 2700chess.com {browsers[i]} | cut -d : -f -1 | grep sqlite_carved | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"sqlite.db {value}")
	
	k=subprocess.check_output(f"grep -a -R 2700chess.com {browsers[i]} | cut -d : -f -1 | grep url_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_histogram.txt {value}")
	
	k=subprocess.check_output(f"grep -a -R 2700chess.com {browsers[i]} | cut -d : -f -1 | grep url.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url.txt {value}")
	print("\n")
	print("\n")
	print("wikipedia.org Data: \n")
	k=subprocess.check_output(f"grep -a -R wikipedia.org {browsers[i]} | cut -d : -f -1 | grep domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domainhistogram.txt {value}")
	
	k=subprocess.check_output(f"grep -a -R wikipedia.org {browsers[i]} | cut -d : -f -1 | grep domain.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domain.txt {value}")
	
	k=subprocess.check_output(f"grep -a -R wikipedia.org {browsers[i]} | cut -d : -f -1 | grep email_domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_domain_histogram.txt {value}")
	
	k=subprocess.check_output(f"grep -a -R wikipedia.org {browsers[i]} | cut -d : -f -1 | grep email_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_histogram.txt {value}")
	
	k=subprocess.check_output(f"grep -a -R wikipedia.org {browsers[i]} | cut -d : -f -1 | grep email.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email.txt {value}")
	
	k=subprocess.check_output(f"grep -a -R wikipedia.org {browsers[i]} | cut -d : -f -1 | grep json.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"json.txt {value}")
	
	k=subprocess.check_output(f"grep -a -R wikipedia.org {browsers[i]} | cut -d : -f -1 | grep url_searches.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_searches.txt {value}")
	
	k=subprocess.check_output(f"grep -a -R wikipedia.org {browsers[i]} | cut -d : -f -1 | grep url_services.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_services.txt {value}")
	
	k=subprocess.check_output(f"grep -a -R wikipedia.org {browsers[i]} | cut -d : -f -1 | grep sqlite_carved | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"sqlite.db {value}")
	
	k=subprocess.check_output(f"grep -a -R wikipedia.org {browsers[i]} | cut -d : -f -1 | grep url_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_histogram.txt {value}")
	print("\n")
	k=subprocess.check_output(f"grep -a -R wikipedia.org {browsers[i]} | cut -d : -f -1 | grep url.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url.txt {value}")
	print("\n")
	print("\n")
	print("uselessweb.com Data: \n")
	k=subprocess.check_output(f"grep -a -R uselessweb.com {browsers[i]} | cut -d : -f -1 | grep domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domainhistogram.txt {value}")
	
	k=subprocess.check_output(f"grep -a -R uselessweb.com {browsers[i]} | cut -d : -f -1 | grep domain.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domain.txt {value}")
	
	k=subprocess.check_output(f"grep -a -R uselessweb.com {browsers[i]} | cut -d : -f -1 | grep email_domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_domain_histogram.txt {value}")
	
	k=subprocess.check_output(f"grep -a -R uselessweb.com {browsers[i]} | cut -d : -f -1 | grep email_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_histogram.txt {value}")
	
	k=subprocess.check_output(f"grep -a -R uselessweb.com {browsers[i]} | cut -d : -f -1 | grep email.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email.txt {value}")
	
	k=subprocess.check_output(f"grep -a -R uselessweb.com {browsers[i]} | cut -d : -f -1 | grep json.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"json.txt {value}")
	
	k=subprocess.check_output(f"grep -a -R uselessweb.com {browsers[i]} | cut -d : -f -1 | grep url_searches.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_searches.txt {value}")
	
	k=subprocess.check_output(f"grep -a -R uselessweb.com {browsers[i]} | cut -d : -f -1 | grep url_services.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_services.txt {value}")
	
	k=subprocess.check_output(f"grep -a -R uselessweb.com {browsers[i]} | cut -d : -f -1 | grep sqlite_carved | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"sqlite.db {value}")
	
	k=subprocess.check_output(f"grep -a -R uselessweb.com {browsers[i]} | cut -d : -f -1 | grep url_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_histogram.txt {value}")
	
	k=subprocess.check_output(f"grep -a -R uselessweb.com {browsers[i]} | cut -d : -f -1 | grep url.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url.txt {value}")
	print("\n")
	print("\n")
	print("reddit.com Data: \n")
	k=subprocess.check_output(f"grep -a -R reddit.com {browsers[i]} | cut -d : -f -1 | grep domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domainhistogram.txt {value}")
	
	k=subprocess.check_output(f"grep -a -R reddit.com {browsers[i]} | cut -d : -f -1 | grep domain.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domain.txt {value}")
	
	k=subprocess.check_output(f"grep -a -R reddit.com {browsers[i]} | cut -d : -f -1 | grep email_domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_domain_histogram.txt {value}")
	
	k=subprocess.check_output(f"grep -a -R reddit.com {browsers[i]} | cut -d : -f -1 | grep email_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_histogram.txt {value}")
	
	k=subprocess.check_output(f"grep -a -R reddit.com {browsers[i]} | cut -d : -f -1 | grep email.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email.txt {value}")
	
	k=subprocess.check_output(f"grep -a -R reddit.com {browsers[i]} | cut -d : -f -1 | grep json.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"json.txt {value}")
	
	k=subprocess.check_output(f"grep -a -R reddit.com {browsers[i]} | cut -d : -f -1 | grep url_searches.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_searches.txt {value}")
	
	k=subprocess.check_output(f"grep -a -R reddit.com {browsers[i]} | cut -d : -f -1 | grep url_services.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_services.txt {value}")
	
	k=subprocess.check_output(f"grep -a -R reddit.com {browsers[i]} | cut -d : -f -1 | grep sqlite_carved | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"sqlite.db {value}")
	
	k=subprocess.check_output(f"grep -a -R reddit.com {browsers[i]} | cut -d : -f -1 | grep url_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_histogram.txt {value}")
	
	k=subprocess.check_output(f"grep -a -R reddit.com {browsers[i]} | cut -d : -f -1 | grep url.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url.txt {value}")
	print("\n")
	print("\n")
	print("duckduckgo.com Data: \n")
	k=subprocess.check_output(f"grep -a -R duckduckgo.com {browsers[i]} | cut -d : -f -1 | grep domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domainhistogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R duckduckgo.com {browsers[i]} | cut -d : -f -1 | grep domain.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domain.txt {value}")
	k=subprocess.check_output(f"grep -a -R duckduckgo.com {browsers[i]} | cut -d : -f -1 | grep email_domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_domain_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R duckduckgo.com {browsers[i]} | cut -d : -f -1 | grep email_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R duckduckgo.com {browsers[i]} | cut -d : -f -1 | grep email.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email.txt {value}")
	k=subprocess.check_output(f"grep -a -R duckduckgo.com {browsers[i]} | cut -d : -f -1 | grep json.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"json.txt {value}")
	k=subprocess.check_output(f"grep -a -R duckduckgo.com {browsers[i]} | cut -d : -f -1 | grep url_searches.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_searches.txt {value}")
	k=subprocess.check_output(f"grep -a -R duckduckgo.com {browsers[i]} | cut -d : -f -1 | grep url_services.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_services.txt {value}")
	k=subprocess.check_output(f"grep -a -R duckduckgo.com {browsers[i]} | cut -d : -f -1 | grep sqlite_carved | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"sqlite.db {value}")
	k=subprocess.check_output(f"grep -a -R duckduckgo.com {browsers[i]} | cut -d : -f -1 | grep url_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R duckduckgo.com {browsers[i]} | cut -d : -f -1 | grep url.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url.txt {value}")
	print("\n")
	print("\n")
	print("yandex.com Data: \n")
	k=subprocess.check_output(f"grep -a -R yandex.com {browsers[i]} | cut -d : -f -1 | grep domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domainhistogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R yandex.com {browsers[i]} | cut -d : -f -1 | grep domain.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domain.txt {value}")
	k=subprocess.check_output(f"grep -a -R yandex.com {browsers[i]} | cut -d : -f -1 | grep email_domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_domain_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R yandex.com {browsers[i]} | cut -d : -f -1 | grep email_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R yandex.com {browsers[i]} | cut -d : -f -1 | grep email.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email.txt {value}")
	k=subprocess.check_output(f"grep -a -R yandex.com {browsers[i]} | cut -d : -f -1 | grep json.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"json.txt {value}")
	k=subprocess.check_output(f"grep -a -R yandex.com {browsers[i]} | cut -d : -f -1 | grep url_searches.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_searches.txt {value}")
	k=subprocess.check_output(f"grep -a -R yandex.com {browsers[i]} | cut -d : -f -1 | grep url_services.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_services.txt {value}")
	k=subprocess.check_output(f"grep -a -R yandex.com {browsers[i]} | cut -d : -f -1 | grep sqlite_carved | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"sqlite.db {value}")
	k=subprocess.check_output(f"grep -a -R yandex.com {browsers[i]} | cut -d : -f -1 | grep url_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R yandex.com {browsers[i]} | cut -d : -f -1 | grep url.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url.txt {value}")
	print("\n")
	print("bing.com Data: \n")
	k=subprocess.check_output(f"grep -a -R bing.com {browsers[i]} | cut -d : -f -1 | grep domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domainhistogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R bing.com {browsers[i]} | cut -d : -f -1 | grep domain.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domain.txt {value}")
	k=subprocess.check_output(f"grep -a -R bing.com {browsers[i]} | cut -d : -f -1 | grep email_domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_domain_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R bing.com {browsers[i]} | cut -d : -f -1 | grep email_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R bing.com {browsers[i]} | cut -d : -f -1 | grep email.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email.txt {value}")
	k=subprocess.check_output(f"grep -a -R bing.com {browsers[i]} | cut -d : -f -1 | grep json.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"json.txt {value}")
	k=subprocess.check_output(f"grep -a -R bing.com {browsers[i]} | cut -d : -f -1 | grep url_searches.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_searches.txt {value}")
	k=subprocess.check_output(f"grep -a -R bing.com {browsers[i]} | cut -d : -f -1 | grep url_services.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_services.txt {value}")
	k=subprocess.check_output(f"grep -a -R bing.com {browsers[i]} | cut -d : -f -1 | grep sqlite_carved | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"sqlite.db {value}")
	k=subprocess.check_output(f"grep -a -R bing.com {browsers[i]} | cut -d : -f -1 | grep url_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R bing.com {browsers[i]} | cut -d : -f -1 | grep url.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url.txt {value}")
	print("\n")
	print("\n")
	print("youtube.com Data: \n")
	k=subprocess.check_output(f"grep -a -R youtube.com {browsers[i]} | cut -d : -f -1 | grep domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domainhistogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R youtube.com {browsers[i]} | cut -d : -f -1 | grep domain.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domain.txt {value}")
	k=subprocess.check_output(f"grep -a -R youtube.com {browsers[i]} | cut -d : -f -1 | grep email_domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_domain_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R youtube.com {browsers[i]} | cut -d : -f -1 | grep email_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R youtube.com {browsers[i]} | cut -d : -f -1 | grep email.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email.txt {value}")
	k=subprocess.check_output(f"grep -a -R youtube.com {browsers[i]} | cut -d : -f -1 | grep json.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"json.txt {value}")
	k=subprocess.check_output(f"grep -a -R youtube.com {browsers[i]} | cut -d : -f -1 | grep url_searches.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_searches.txt {value}")
	k=subprocess.check_output(f"grep -a -R youtube.com {browsers[i]} | cut -d : -f -1 | grep url_services.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_services.txt {value}")
	k=subprocess.check_output(f"grep -a -R youtube.com {browsers[i]} | cut -d : -f -1 | grep sqlite_carved | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"sqlite.db {value}")
	k=subprocess.check_output(f"grep -a -R youtube.com {browsers[i]} | cut -d : -f -1 | grep url_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R youtube.com {browsers[i]} | cut -d : -f -1 | grep url.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url.txt {value}")
	print("\n")
	print("\n")
	print("anonymous2_email_research_test Data: \n")
	k=subprocess.check_output(f"grep -a -R anonymous2_email_research_test {browsers[i]} | cut -d : -f -1 | grep domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domainhistogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R anonymous2_email_research_test {browsers[i]} | cut -d : -f -1 | grep domain.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domain.txt {value}")
	k=subprocess.check_output(f"grep -a -R anonymous2_email_research_test {browsers[i]} | cut -d : -f -1 | grep email_domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_domain_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R anonymous2_email_research_test {browsers[i]} | cut -d : -f -1 | grep email_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R anonymous2_email_research_test {browsers[i]} | cut -d : -f -1 | grep email.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email.txt {value}")
	k=subprocess.check_output(f"grep -a -R anonymous2_email_research_test {browsers[i]} | cut -d : -f -1 | grep json.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"json.txt {value}")
	k=subprocess.check_output(f"grep -a -R anonymous2_email_research_test {browsers[i]} | cut -d : -f -1 | grep url_searches.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_searches.txt {value}")
	k=subprocess.check_output(f"grep -a -R anonymous2_email_research_test {browsers[i]} | cut -d : -f -1 | grep url_services.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_services.txt {value}")
	k=subprocess.check_output(f"grep -a -R anonymous2_email_research_test {browsers[i]} | cut -d : -f -1 | grep sqlite_carved | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"sqlite.db {value}")
	k=subprocess.check_output(f"grep -a -R anonymous2_email_research_test {browsers[i]} | cut -d : -f -1 | grep url_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R anonymous2_email_research_test {browsers[i]} | cut -d : -f -1 | grep url.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url.txt {value}")
	print("\n")
	print("\n")
	print("continental2_email_research_test Data: \n")
	k=subprocess.check_output(f"grep -a -R continental2_email_research_test {browsers[i]} | cut -d : -f -1 | grep domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domainhistogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R continental2_email_research_test {browsers[i]} | cut -d : -f -1 | grep domain.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domain.txt {value}")
	k=subprocess.check_output(f"grep -a -R continental2_email_research_test {browsers[i]} | cut -d : -f -1 | grep email_domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_domain_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R continental2_email_research_test {browsers[i]} | cut -d : -f -1 | grep email_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R continental2_email_research_test {browsers[i]} | cut -d : -f -1 | grep email.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email.txt {value}")
	k=subprocess.check_output(f"grep -a -R continental2_email_research_test {browsers[i]} | cut -d : -f -1 | grep json.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"json.txt {value}")
	k=subprocess.check_output(f"grep -a -R continental2_email_research_test {browsers[i]} | cut -d : -f -1 | grep url_searches.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_searches.txt {value}")
	k=subprocess.check_output(f"grep -a -R continental2_email_research_test {browsers[i]} | cut -d : -f -1 | grep url_services.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_services.txt {value}")
	k=subprocess.check_output(f"grep -a -R continental2_email_research_test {browsers[i]} | cut -d : -f -1 | grep sqlite_carved | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"sqlite.db {value}")
	k=subprocess.check_output(f"grep -a -R continental2_email_research_test {browsers[i]} | cut -d : -f -1 | grep url_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R continental2_email_research_test {browsers[i]} | cut -d : -f -1 | grep url.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url.txt {value}")
	print("\n")
	print("\n")
	print("private2_email_research_test Data: \n")
	k=subprocess.check_output(f"grep -a -R private2_email_research_test {browsers[i]} | cut -d : -f -1 | grep domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domainhistogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R private2_email_research_test {browsers[i]} | cut -d : -f -1 | grep domain.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domain.txt {value}")
	k=subprocess.check_output(f"grep -a -R private2_email_research_test {browsers[i]} | cut -d : -f -1 | grep email_domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_domain_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R private2_email_research_test {browsers[i]} | cut -d : -f -1 | grep email_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R private2_email_research_test {browsers[i]} | cut -d : -f -1 | grep email.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email.txt {value}")
	k=subprocess.check_output(f"grep -a -R private2_email_research_test {browsers[i]} | cut -d : -f -1 | grep json.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"json.txt {value}")
	k=subprocess.check_output(f"grep -a -R private2_email_research_test {browsers[i]} | cut -d : -f -1 | grep url_searches.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_searches.txt {value}")
	k=subprocess.check_output(f"grep -a -R private2_email_research_test {browsers[i]} | cut -d : -f -1 | grep url_services.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_services.txt {value}")
	k=subprocess.check_output(f"grep -a -R private2_email_research_test {browsers[i]} | cut -d : -f -1 | grep sqlite_carved | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"sqlite.db {value}")
	k=subprocess.check_output(f"grep -a -R private2_email_research_test {browsers[i]} | cut -d : -f -1 | grep url_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R private2_email_research_test {browsers[i]} | cut -d : -f -1 | grep url.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url.txt {value}")
	print("\n")
	print("\n")
	print("Content_search_research_test Data: \n")
	k=subprocess.check_output(f"grep -a -R Content_search_research_test {browsers[i]} | cut -d : -f -1 | grep domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domainhistogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Content_search_research_test {browsers[i]} | cut -d : -f -1 | grep domain.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domain.txt {value}")
	k=subprocess.check_output(f"grep -a -R Content_search_research_test {browsers[i]} | cut -d : -f -1 | grep email_domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_domain_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Content_search_research_test {browsers[i]} | cut -d : -f -1 | grep email_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Content_search_research_test {browsers[i]} | cut -d : -f -1 | grep email.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email.txt {value}")
	k=subprocess.check_output(f"grep -a -R Content_search_research_test {browsers[i]} | cut -d : -f -1 | grep json.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"json.txt {value}")
	k=subprocess.check_output(f"grep -a -R Content_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_searches.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_searches.txt {value}")
	k=subprocess.check_output(f"grep -a -R Content_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_services.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_services.txt {value}")
	k=subprocess.check_output(f"grep -a -R Content_search_research_test {browsers[i]} | cut -d : -f -1 | grep sqlite_carved | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"sqlite.db {value}")
	k=subprocess.check_output(f"grep -a -R Content_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Content_search_research_test {browsers[i]} | cut -d : -f -1 | grep url.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url.txt {value}")
	print("\n")
	print("\n")
	print("Convict_search_research_test Data: \n")
	k=subprocess.check_output(f"grep -a -R Convict_search_research_test {browsers[i]} | cut -d : -f -1 | grep domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domainhistogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Convict_search_research_test {browsers[i]} | cut -d : -f -1 | grep domain.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domain.txt {value}")
	k=subprocess.check_output(f"grep -a -R Convict_search_research_test {browsers[i]} | cut -d : -f -1 | grep email_domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_domain_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Convict_search_research_test {browsers[i]} | cut -d : -f -1 | grep email_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Convict_search_research_test {browsers[i]} | cut -d : -f -1 | grep email.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email.txt {value}")
	k=subprocess.check_output(f"grep -a -R Convict_search_research_test {browsers[i]} | cut -d : -f -1 | grep json.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"json.txt {value}")
	k=subprocess.check_output(f"grep -a -R Convict_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_searches.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_searches.txt {value}")
	k=subprocess.check_output(f"grep -a -R Convict_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_services.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_services.txt {value}")
	k=subprocess.check_output(f"grep -a -R Convict_search_research_test {browsers[i]} | cut -d : -f -1 | grep sqlite_carved | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"sqlite.db {value}")
	k=subprocess.check_output(f"grep -a -R Convict_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Convict_search_research_test {browsers[i]} | cut -d : -f -1 | grep url.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url.txt {value}")
	print("\n")
	print("\n")
	print("Symptom_search_research_test Data: \n")
	k=subprocess.check_output(f"grep -a -R Symptom_search_research_test {browsers[i]} | cut -d : -f -1 | grep domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domainhistogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Symptom_search_research_test {browsers[i]} | cut -d : -f -1 | grep domain.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domain.txt {value}")
	k=subprocess.check_output(f"grep -a -R Symptom_search_research_test {browsers[i]} | cut -d : -f -1 | grep email_domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_domain_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Symptom_search_research_test {browsers[i]} | cut -d : -f -1 | grep email_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Symptom_search_research_test {browsers[i]} | cut -d : -f -1 | grep email.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email.txt {value}")
	k=subprocess.check_output(f"grep -a -R Symptom_search_research_test {browsers[i]} | cut -d : -f -1 | grep json.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"json.txt {value}")
	k=subprocess.check_output(f"grep -a -R Symptom_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_searches.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_searches.txt {value}")
	k=subprocess.check_output(f"grep -a -R Symptom_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_services.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_services.txt {value}")
	k=subprocess.check_output(f"grep -a -R Symptom_search_research_test {browsers[i]} | cut -d : -f -1 | grep sqlite_carved | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"sqlite.db {value}")
	k=subprocess.check_output(f"grep -a -R Symptom_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Symptom_search_research_test {browsers[i]} | cut -d : -f -1 | grep url.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url.txt {value}")
	print("\n")
	print("\n")
	print("Deprive_search_research_test Data: \n")
	k=subprocess.check_output(f"grep -a -R Deprive_search_research_test {browsers[i]} | cut -d : -f -1 | grep domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domainhistogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Deprive_search_research_test {browsers[i]} | cut -d : -f -1 | grep domain.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domain.txt {value}")
	k=subprocess.check_output(f"grep -a -R Deprive_search_research_test {browsers[i]} | cut -d : -f -1 | grep email_domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_domain_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Deprive_search_research_test {browsers[i]} | cut -d : -f -1 | grep email_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Deprive_search_research_test {browsers[i]} | cut -d : -f -1 | grep email.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email.txt {value}")
	k=subprocess.check_output(f"grep -a -R Deprive_search_research_test {browsers[i]} | cut -d : -f -1 | grep json.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"json.txt {value}")
	k=subprocess.check_output(f"grep -a -R Deprive_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_searches.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_searches.txt {value}")
	k=subprocess.check_output(f"grep -a -R Deprive_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_services.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_services.txt {value}")
	k=subprocess.check_output(f"grep -a -R Deprive_search_research_test {browsers[i]} | cut -d : -f -1 | grep sqlite_carved | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"sqlite.db {value}")
	k=subprocess.check_output(f"grep -a -R Deprive_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Deprive_search_research_test {browsers[i]} | cut -d : -f -1 | grep url.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url.txt {value}")
	print("\n")
	print("\n")
	print("Nightmare_search_research_test Data: \n")
	k=subprocess.check_output(f"grep -a -R Nightmare_search_research_test {browsers[i]} | cut -d : -f -1 | grep domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domainhistogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Nightmare_search_research_test {browsers[i]} | cut -d : -f -1 | grep domain.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domain.txt {value}")
	k=subprocess.check_output(f"grep -a -R Nightmare_search_research_test {browsers[i]} | cut -d : -f -1 | grep email_domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_domain_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Nightmare_search_research_test {browsers[i]} | cut -d : -f -1 | grep email_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Nightmare_search_research_test {browsers[i]} | cut -d : -f -1 | grep email.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email.txt {value}")
	k=subprocess.check_output(f"grep -a -R Nightmare_search_research_test {browsers[i]} | cut -d : -f -1 | grep json.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"json.txt {value}")
	k=subprocess.check_output(f"grep -a -R Nightmare_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_searches.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_searches.txt {value}")
	k=subprocess.check_output(f"grep -a -R Nightmare_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_services.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_services.txt {value}")
	k=subprocess.check_output(f"grep -a -R Nightmare_search_research_test {browsers[i]} | cut -d : -f -1 | grep sqlite_carved | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"sqlite.db {value}")
	k=subprocess.check_output(f"grep -a -R Nightmare_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Nightmare_search_research_test {browsers[i]} | cut -d : -f -1 | grep url.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url.txt {value}")
	print("\n")
	print("Flood_search_research_test Data: \n")
	k=subprocess.check_output(f"grep -a -R Flood_search_research_test {browsers[i]} | cut -d : -f -1 | grep domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domainhistogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Flood_search_research_test {browsers[i]} | cut -d : -f -1 | grep domain.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domain.txt {value}")
	k=subprocess.check_output(f"grep -a -R Flood_search_research_test {browsers[i]} | cut -d : -f -1 | grep email_domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_domain_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Flood_search_research_test {browsers[i]} | cut -d : -f -1 | grep email_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Flood_search_research_test {browsers[i]} | cut -d : -f -1 | grep email.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email.txt {value}")
	k=subprocess.check_output(f"grep -a -R Flood_search_research_test {browsers[i]} | cut -d : -f -1 | grep json.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"json.txt {value}")
	k=subprocess.check_output(f"grep -a -R Flood_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_searches.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_searches.txt {value}")
	k=subprocess.check_output(f"grep -a -R Flood_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_services.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_services.txt {value}")
	k=subprocess.check_output(f"grep -a -R Flood_search_research_test {browsers[i]} | cut -d : -f -1 | grep sqlite_carved | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"sqlite.db {value}")
	k=subprocess.check_output(f"grep -a -R Flood_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Flood_search_research_test {browsers[i]} | cut -d : -f -1 | grep url.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url.txt {value}")
	print("\n")
	print("Craftsman_search_research_test Data: \n")
	k=subprocess.check_output(f"grep -a -R Craftsman_search_research_test {browsers[i]} | cut -d : -f -1 | grep domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domainhistogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Craftsman_search_research_test {browsers[i]} | cut -d : -f -1 | grep domain.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domain.txt {value}")
	k=subprocess.check_output(f"grep -a -R Craftsman_search_research_test {browsers[i]} | cut -d : -f -1 | grep email_domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_domain_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Craftsman_search_research_test {browsers[i]} | cut -d : -f -1 | grep email_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Craftsman_search_research_test {browsers[i]} | cut -d : -f -1 | grep email.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email.txt {value}")
	k=subprocess.check_output(f"grep -a -R Craftsman_search_research_test {browsers[i]} | cut -d : -f -1 | grep json.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"json.txt {value}")
	k=subprocess.check_output(f"grep -a -R Craftsman_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_searches.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_searches.txt {value}")
	k=subprocess.check_output(f"grep -a -R Craftsman_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_services.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_services.txt {value}")
	k=subprocess.check_output(f"grep -a -R Craftsman_search_research_test {browsers[i]} | cut -d : -f -1 | grep sqlite_carved | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"sqlite.db {value}")
	k=subprocess.check_output(f"grep -a -R Craftsman_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Craftsman_search_research_test {browsers[i]} | cut -d : -f -1 | grep url.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url.txt {value}")
	print("\n")
	print("Tolerate_search_research_test Data: \n")
	k=subprocess.check_output(f"grep -a -R Tolerate_search_research_test {browsers[i]} | cut -d : -f -1 | grep domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domainhistogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Tolerate_search_research_test {browsers[i]} | cut -d : -f -1 | grep domain.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domain.txt {value}")
	k=subprocess.check_output(f"grep -a -R Tolerate_search_research_test {browsers[i]} | cut -d : -f -1 | grep email_domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_domain_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Tolerate_search_research_test {browsers[i]} | cut -d : -f -1 | grep email_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Tolerate_search_research_test {browsers[i]} | cut -d : -f -1 | grep email.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email.txt {value}")
	k=subprocess.check_output(f"grep -a -R Tolerate_search_research_test {browsers[i]} | cut -d : -f -1 | grep json.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"json.txt {value}")
	k=subprocess.check_output(f"grep -a -R Tolerate_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_searches.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_searches.txt {value}")
	k=subprocess.check_output(f"grep -a -R Tolerate_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_services.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_services.txt {value}")
	k=subprocess.check_output(f"grep -a -R Tolerate_search_research_test {browsers[i]} | cut -d : -f -1 | grep sqlite_carved | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"sqlite.db {value}")
	k=subprocess.check_output(f"grep -a -R Tolerate_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Tolerate_search_research_test {browsers[i]} | cut -d : -f -1 | grep url.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url.txt {value}")
	print("\n")
	print("Flow_search_research_test Data: \n")
	k=subprocess.check_output(f"grep -a -R Flow_search_research_test {browsers[i]} | cut -d : -f -1 | grep domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domainhistogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Flow_search_research_test {browsers[i]} | cut -d : -f -1 | grep domain.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domain.txt {value}")
	k=subprocess.check_output(f"grep -a -R Flow_search_research_test {browsers[i]} | cut -d : -f -1 | grep email_domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_domain_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Flow_search_research_test {browsers[i]} | cut -d : -f -1 | grep email_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Flow_search_research_test {browsers[i]} | cut -d : -f -1 | grep email.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email.txt {value}")
	k=subprocess.check_output(f"grep -a -R Flow_search_research_test {browsers[i]} | cut -d : -f -1 | grep json.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"json.txt {value}")
	k=subprocess.check_output(f"grep -a -R Flow_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_searches.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_searches.txt {value}")
	k=subprocess.check_output(f"grep -a -R Flow_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_services.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_services.txt {value}")
	k=subprocess.check_output(f"grep -a -R Flow_search_research_test {browsers[i]} | cut -d : -f -1 | grep sqlite_carved | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"sqlite.db {value}")
	k=subprocess.check_output(f"grep -a -R Flow_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Flow_search_research_test {browsers[i]} | cut -d : -f -1 | grep url.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url.txt {value}")
	print("\n")
	print("Spill_search_research_test Data: \n")
	k=subprocess.check_output(f"grep -a -R Spill_search_research_test {browsers[i]} | cut -d : -f -1 | grep domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domainhistogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Spill_search_research_test {browsers[i]} | cut -d : -f -1 | grep domain.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domain.txt {value}")
	k=subprocess.check_output(f"grep -a -R Spill_search_research_test {browsers[i]} | cut -d : -f -1 | grep email_domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_domain_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Spill_search_research_test {browsers[i]} | cut -d : -f -1 | grep email_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Spill_search_research_test {browsers[i]} | cut -d : -f -1 | grep email.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email.txt {value}")
	k=subprocess.check_output(f"grep -a -R Spill_search_research_test {browsers[i]} | cut -d : -f -1 | grep json.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"json.txt {value}")
	k=subprocess.check_output(f"grep -a -R Spill_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_searches.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_searches.txt {value}")
	k=subprocess.check_output(f"grep -a -R Spill_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_services.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_services.txt {value}")
	k=subprocess.check_output(f"grep -a -R Spill_search_research_test {browsers[i]} | cut -d : -f -1 | grep sqlite_carved | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"sqlite.db {value}")
	k=subprocess.check_output(f"grep -a -R Spill_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Spill_search_research_test {browsers[i]} | cut -d : -f -1 | grep url.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url.txt {value}")
	print("\n")
	print("Intrusion_search_research_test Data: \n")
	k=subprocess.check_output(f"grep -a -R Intrusion_search_research_test {browsers[i]} | cut -d : -f -1 | grep domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domainhistogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Intrusion_search_research_test {browsers[i]} | cut -d : -f -1 | grep domain.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domain.txt {value}")
	k=subprocess.check_output(f"grep -a -R Intrusion_search_research_test {browsers[i]} | cut -d : -f -1 | grep email_domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_domain_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Intrusion_search_research_test {browsers[i]} | cut -d : -f -1 | grep email_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Intrusion_search_research_test {browsers[i]} | cut -d : -f -1 | grep email.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email.txt {value}")
	k=subprocess.check_output(f"grep -a -R Intrusion_search_research_test {browsers[i]} | cut -d : -f -1 | grep json.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"json.txt {value}")
	k=subprocess.check_output(f"grep -a -R Intrusion_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_searches.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_searches.txt {value}")
	k=subprocess.check_output(f"grep -a -R Intrusion_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_services.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_services.txt {value}")
	k=subprocess.check_output(f"grep -a -R Intrusion_search_research_test {browsers[i]} | cut -d : -f -1 | grep sqlite_carved | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"sqlite.db {value}")
	k=subprocess.check_output(f"grep -a -R Intrusion_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Intrusion_search_research_test {browsers[i]} | cut -d : -f -1 | grep url.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url.txt {value}")
	print("\n")
	print("Infiltrate_search_research_test Data: \n")
	k=subprocess.check_output(f"grep -a -R Infiltrate_search_research_test {browsers[i]} | cut -d : -f -1 | grep domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domainhistogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Infiltrate_search_research_test {browsers[i]} | cut -d : -f -1 | grep domain.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domain.txt {value}")
	k=subprocess.check_output(f"grep -a -R Infiltrate_search_research_test {browsers[i]} | cut -d : -f -1 | grep email_domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_domain_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Infiltrate_search_research_test {browsers[i]} | cut -d : -f -1 | grep email_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Infiltrate_search_research_test {browsers[i]} | cut -d : -f -1 | grep email.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email.txt {value}")
	k=subprocess.check_output(f"grep -a -R Infiltrate_search_research_test {browsers[i]} | cut -d : -f -1 | grep json.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"json.txt {value}")
	k=subprocess.check_output(f"grep -a -R Infiltrate_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_searches.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_searches.txt {value}")
	k=subprocess.check_output(f"grep -a -R Infiltrate_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_services.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_services.txt {value}")
	k=subprocess.check_output(f"grep -a -R Infiltrate_search_research_test {browsers[i]} | cut -d : -f -1 | grep sqlite_carved | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"sqlite.db {value}")
	k=subprocess.check_output(f"grep -a -R Infiltrate_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Infiltrate_search_research_test {browsers[i]} | cut -d : -f -1 | grep url.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url.txt {value}")
	print("\n")
	print("Conclude_search_research_test Data: \n")
	k=subprocess.check_output(f"grep -a -R Conclude_search_research_test {browsers[i]} | cut -d : -f -1 | grep domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domainhistogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Conclude_search_research_test {browsers[i]} | cut -d : -f -1 | grep domain.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domain.txt {value}")
	k=subprocess.check_output(f"grep -a -R Conclude_search_research_test {browsers[i]} | cut -d : -f -1 | grep email_domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_domain_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Conclude_search_research_test {browsers[i]} | cut -d : -f -1 | grep email_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Conclude_search_research_test {browsers[i]} | cut -d : -f -1 | grep email.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email.txt {value}")
	k=subprocess.check_output(f"grep -a -R Conclude_search_research_test {browsers[i]} | cut -d : -f -1 | grep json.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"json.txt {value}")
	k=subprocess.check_output(f"grep -a -R Conclude_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_searches.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_searches.txt {value}")
	k=subprocess.check_output(f"grep -a -R Conclude_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_services.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_services.txt {value}")
	k=subprocess.check_output(f"grep -a -R Conclude_search_research_test {browsers[i]} | cut -d : -f -1 | grep sqlite_carved | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"sqlite.db {value}")
	k=subprocess.check_output(f"grep -a -R Conclude_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Conclude_search_research_test {browsers[i]} | cut -d : -f -1 | grep url.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url.txt {value}")
	print("\n")
	print("Confirm_search_research_test Data: \n")
	k=subprocess.check_output(f"grep -a -R Confirm_search_research_test {browsers[i]} | cut -d : -f -1 | grep domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domainhistogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Confirm_search_research_test {browsers[i]} | cut -d : -f -1 | grep domain.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"domain.txt {value}")
	k=subprocess.check_output(f"grep -a -R Confirm_search_research_test {browsers[i]} | cut -d : -f -1 | grep email_domain_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_domain_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Confirm_search_research_test {browsers[i]} | cut -d : -f -1 | grep email_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Confirm_search_research_test {browsers[i]} | cut -d : -f -1 | grep email.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"email.txt {value}")
	k=subprocess.check_output(f"grep -a -R Confirm_search_research_test {browsers[i]} | cut -d : -f -1 | grep json.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"json.txt {value}")
	k=subprocess.check_output(f"grep -a -R Confirm_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_searches.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_searches.txt {value}")
	k=subprocess.check_output(f"grep -a -R Confirm_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_services.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_services.txt {value}")
	k=subprocess.check_output(f"grep -a -R Confirm_search_research_test {browsers[i]} | cut -d : -f -1 | grep sqlite_carved | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"sqlite.db {value}")
	k=subprocess.check_output(f"grep -a -R Confirm_search_research_test {browsers[i]} | cut -d : -f -1 | grep url_histogram.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url_histogram.txt {value}")
	k=subprocess.check_output(f"grep -a -R Confirm_search_research_test {browsers[i]} | cut -d : -f -1 | grep url.txt | sort -d | wc -l",shell=True)
	value=int(k.decode("utf-8"))
	print(f"url.txt {value}")
	print("\n")
	print("\n")
	print("\n")











	
	
	
	
